---
- name: exploring facts
  become: no
  hosts: all
  tasks:
    - name: print os
      ansible.builtin.debug:
        msg:  "{{ ansible_facts['os_family'] }}"
---
- name: exploring facts
  become: no
  hosts: all
  tasks:
    - name: print os
      ansible.builtin.debug:
        msg:  "family: {{ ansible_facts['os_family'] }}"

---
- name: exploring facts
  become: no
  hosts: all
  tasks:
    - name: print os
      ansible.builtin.debug:
        msg: "family: {{ ansible_facts['os_family'] }}, distribution: {{ ansible_facts['distribution'] }}"

---
- name: exploring facts
  become: no
  hosts: all
  tasks:
    - name: print os
      ansible.builtin.debug:
        msg: "family: {{ ansible_facts['os_family'] }}, distribution: {{ ansible_facts['distribution'] }}"
    - name: print os
      ansible.builtin.debug:
        msg: " ip: {{ ansible_facts['default_ipv4']['address='] }}"
  

