# Manual steps for lamp server installation
# sudo apt update
# sudo apt install apache2 -y
# sudo apt install mysql-server -y
# sudo apt install php libapache2-mod-php php-mysql -y
# sudo -i 
   # /var/www/html/info.php
   # <?php phpinfo (); ?>
   # These command for to set the php path in sudoers user
   #exit
# sudo systemctl restart apache2
# check the node public ip /info.php

---
- name: installation of lamp
  hosts: ubuntu # if we give ' all ' it will run in redhat also it will fail
  become: yes
  tasks:
    - name: Update packages installing ubuntu
      ansible.builtin.apt:
          name: apache2
          update_cache: yes
          state: present
    - name: installing php packages
      ansible.builtin.apt:
        name:
          - php
          - libapache2-mod-php
          - php-mysql
        state: present
      notify:
        - restart ubuntu
    - name: copy the info.php
      ansible.builtin.copy:
        src: info.php
        dest: /var/www/html/info.php 
      notify:
        - restart ubuntu    
  handlers:
    - name: restart ubuntu
      ansible.builtin.systemd:
        name: apache2
        state: restarted
      

        
      
      


      
    
